project:
  type: website
  output-dir: docs

website:
  title: "Nathalie Bonnet"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: media.qmd
        text: Media

format:
  html:
    theme: flatly
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full



